"""name_en is not unique for food

Revision ID: 0da754909900
Revises: 394d12935a91
Create Date: 2019-01-22 23:59:47.384383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da754909900'
down_revision = '394d12935a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_food_name_en', table_name='food')
    op.create_index(op.f('ix_food_name_en'), 'food', ['name_en'], unique=False)
    op.drop_index('ix_food_name_fr', table_name='food')
    op.create_index(op.f('ix_food_name_fr'), 'food', ['name_fr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_name_fr'), table_name='food')
    op.create_index('ix_food_name_fr', 'food', ['name_fr'], unique=1)
    op.drop_index(op.f('ix_food_name_en'), table_name='food')
    op.create_index('ix_food_name_en', 'food', ['name_en'], unique=1)
    # ### end Alembic commands ###
