"""add code to sub sub group

Revision ID: 394d12935a91
Revises: 4870e1f7a7f1
Create Date: 2019-01-22 23:44:51.791514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394d12935a91'
down_revision = '4870e1f7a7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_sub_group', sa.Column('code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_sub_group', 'code')
    # ### end Alembic commands ###
