"""add of groups food and compo and source

Revision ID: 4870e1f7a7f1
Revises: 0fc23ec555f4
Create Date: 2019-01-22 19:48:50.835360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4870e1f7a7f1'
down_revision = '0fc23ec555f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=256), nullable=True),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_name_en'), 'component', ['name_en'], unique=True)
    op.create_index(op.f('ix_component_name_fr'), 'component', ['name_fr'], unique=True)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=256), nullable=True),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name_en'), 'group', ['name_en'], unique=True)
    op.create_index(op.f('ix_group_name_fr'), 'group', ['name_fr'], unique=True)
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_citation', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_ref_citation'), 'source', ['ref_citation'], unique=False)
    op.create_table('sub_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=256), nullable=True),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_group_name_en'), 'sub_group', ['name_en'], unique=True)
    op.create_index(op.f('ix_sub_group_name_fr'), 'sub_group', ['name_fr'], unique=True)
    op.create_table('sub_sub_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=256), nullable=True),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('sub_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_group_id'], ['sub_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_sub_group_name_en'), 'sub_sub_group', ['name_en'], unique=False)
    op.create_index(op.f('ix_sub_sub_group_name_fr'), 'sub_sub_group', ['name_fr'], unique=False)
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=256), nullable=True),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('sub_sub_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sub_sub_group_id'], ['sub_sub_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_name_en'), 'food', ['name_en'], unique=True)
    op.create_index(op.f('ix_food_name_fr'), 'food', ['name_fr'], unique=True)
    op.create_table('food_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('trust_code', sa.CHAR(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_component')
    op.drop_index(op.f('ix_food_name_fr'), table_name='food')
    op.drop_index(op.f('ix_food_name_en'), table_name='food')
    op.drop_table('food')
    op.drop_index(op.f('ix_sub_sub_group_name_fr'), table_name='sub_sub_group')
    op.drop_index(op.f('ix_sub_sub_group_name_en'), table_name='sub_sub_group')
    op.drop_table('sub_sub_group')
    op.drop_index(op.f('ix_sub_group_name_fr'), table_name='sub_group')
    op.drop_index(op.f('ix_sub_group_name_en'), table_name='sub_group')
    op.drop_table('sub_group')
    op.drop_index(op.f('ix_source_ref_citation'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_group_name_fr'), table_name='group')
    op.drop_index(op.f('ix_group_name_en'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_component_name_fr'), table_name='component')
    op.drop_index(op.f('ix_component_name_en'), table_name='component')
    op.drop_table('component')
    # ### end Alembic commands ###
